### PR TITLE
Group checkboxes by optgroup label

### LINKED ISSUE #5: Group checkboxes according to <OPTGROUP>
In our design we will have checkboxes grouped in some categories:

image

However, the current version of the lib does not support it. 

I think the most semantic will be to utilize `<OPTGROUP>` element from the HTML like in this example:
```
    <select id="wpforms-entries-table-edit-columns-select" class="wpforms-entries-table-edit-columns-select" name="wpforms-entries-table-edit-columns-select" multiple="multiple">
      <optgroup label="Form Fields">
        <option value="name">Name</option>
        <option value="require_signature">Require signature</option>
        <option value="receiver">Receiver</option>
        <option value="email">Email</option>
        <option value="delivery_date">Delivery date</option>
      </optgroup>
      <optgroup label="Entry Meta">
        <option value="entry_date">Entry Date</option>
        <option value="entry_id">Entry ID</option>
        <option value="entry_notes">Entry Notes</option>
      </optgroup>
    </select>
```
We should read optgroup label, and place it before the first of option from the group:

image

I have the code ready and I will submit it in a moment in the PR.

### PR DESCRIPTION
**Pull request by kkarpieszuk**
Fixes #5 

See the #5 for the description how it works and how it looks. 

Please notice I did not apply any styling for the `<h3>` grouping elements, @mahdiyazdani if you want to have some styles, feel free to add the ones which will align with the rest of rules you already created. For the purposes of my task I will be re-styling your lib a bit so I will define `<h3>` styles there anyway.

### CODE REVIEW

**Comment by kkarpieszuk** [comment]
@mahdiyazdani if you want to see it in action, switch wpforms to commit https://github.com/awesomemotive/wpforms-plugin/pull/8341/commits/de92bbc36e4406c2ac3a60a0dd858eeadf2845be and visit wpforms > entries > select any form with entries > click gear icon in the top right corner of the table

**Review by mahdiyazdani — CHANGES_REQUESTED** [review]
Thank you for your contribution. Please find my comments below:

1. Please consider converting the `<h3>` label tag to a `<span>`. This change will make it easier to add additional styles and make customizations where necessary. Heading tags often have unique styles universally and may not be the best choice for controlling and making design adjustments.

2. Additionally, it would be great if you could align the styles with the Figma design. The dropdown menu is designed with inspiration from the WPForms styling hierarchy.

3. One more important point is that the group label should be made unselectable to avoid interrupting the user when interacting with checkboxes. You can achieve this by adding `user-select: none;` to the option group tag in the CSS.

**Comment by kkarpieszuk** [comment]
> Additionally, it would be great if you could align the styles with the Figma design. 

@mahdiyazdani do you mean the Figma design @mattbrett has created for our rock ( [this one](https://www.figma.com/file/VlyWHl5LXSHs9UhQroP62v/WPForms---Column-Management?type=design&node-id=121-2996&mode=design&t=2V34KtmIaxZa4Q5p-0) ) or do you mean you have some other Figma design exactly for your library somewhere? If the other one, could you share a link? If the first one just please confirm it

**Comment by mahdiyazdani** [comment]
> @mahdiyazdani do you mean the Figma design @mattbrett has created for our rock ( [this one](https://www.figma.com/file/VlyWHl5LXSHs9UhQroP62v/WPForms---Column-Management?type=design&node-id=121-2996&mode=design&t=2V34KtmIaxZa4Q5p-0) ) or do you mean you have some other Figma design exactly for your library somewhere? If the other one, could you share a link? If the first one just please confirm it

@kkarpieszuk I was referring to the Figma design that you were provided for your task.

**Comment by mattbrett** [comment]
If you need various states for the checkboxes, you can find them in the [Style Guide as part of the Settings Design Library](https://www.figma.com/file/XvocpIVeXIqA87ODCthNK2/WPForms---Settings-Design-Library?type=design&node-id=1237%3A1557&mode=design&t=qy9xyZoOkJ55zYKn-1).

**Comment by kkarpieszuk** [comment]
Thank you @mahdiyazdani ( and @mattbrett ), I changed this PR:
- changed element from h3 to span
- added styling
- added demo to the doc

Mahdi, please continue your review

image

**Review by mahdiyazdani — APPROVED** [review]
Thank you @kkarpieszuk 🙌

**Pull request merged**
