### PR TITLE
Add customOpener configuration option and handle clicks

### LINKED ISSUE #3: Allow opening menu from custom selector
Hi @mahdiyazdani 

for the purpose to adapt your library into WPForms column selector I had to make it possible trigger opening the menu from a gear icon, like this:

vokoscreenNG-2023-10-19_12-49-10

Current version recognizes any click outside itself as a case to close menu. 

I made it configurable to specify CSS selector for custom opener. 

In a moment I will submit the PR

### PR DESCRIPTION
**Pull request by kkarpieszuk**
Fixes #3 

Test steps:
- add select element which you want multiselect to be applied for
- add some `<button id="foo">`
- initialize multiselect with option `customOpener: '#foo'`
- click the button and make sure multiselect is open

You can see this in real use on this branch of WPForms:
https://github.com/awesomemotive/wpforms-plugin/pull/8341/commits/12d59d1b75ea3717ae43784bfd913f9df7282016
- go to WPForms > Entries > Select some form with entries
- on the entries list page click gear icon in right top corner of the table
- 
vokoscreenNG-2023-10-19_12-49-10

### CODE REVIEW

**Review by mahdiyazdani — CHANGES_REQUESTED** [review]
Thank you for your contribution here. Please see my comments below:

Based on the options property name, which suggests “customOpener”, I would recommend passing a single DOM element to the opener argument. This approach would eliminate the need to loop through multiple opener elements, as it is uncommon to have more than one opener for a single dropdown menu.

Additionally, please see the following non-blocker issues as well:

- It seems he didn’t build and compile the final package for distributed files. See the repository readme file in creating dist files.
- No demo is added to the [demo website](https://awesomemotive.github.io/wpforms-multiselect-js/).
- No documentation is added to the “Settings” table on the demo website.

**Comment by kkarpieszuk** [comment]
Thank you @mahdiyazdani for the review. I applied all your suggested changes, including the update od the demo. Please review again

**Review by mahdiyazdani — APPROVED** [review]
Thank you @kkarpieszuk 🙌

**Review by mahdiyazdani — APPROVED** [review]
Thank you @kkarpieszuk 🙌

**Pull request merged**
